// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWVQEFVcUnJ4x7C-f0aaTVVA4AHQhv80',
    appId: '1:997215765874:web:52519aa68be37b8d5449eb',
    messagingSenderId: '997215765874',
    projectId: 'medi-gaze-eec58',
    authDomain: 'medi-gaze-eec58.firebaseapp.com',
    storageBucket: 'medi-gaze-eec58.appspot.com',
    measurementId: 'G-ZLM52H4HNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7EQ6KPZ52xPBOS0zDGLfhlpWvArK-lo',
    appId: '1:997215765874:android:3c697495f09362965449eb',
    messagingSenderId: '997215765874',
    projectId: 'medi-gaze-eec58',
    storageBucket: 'medi-gaze-eec58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcDvgtdvDw3zxL4TCEXxHKwC9MNjwcJI8',
    appId: '1:997215765874:ios:1a5c14535724a5655449eb',
    messagingSenderId: '997215765874',
    projectId: 'medi-gaze-eec58',
    storageBucket: 'medi-gaze-eec58.appspot.com',
    iosBundleId: 'com.example.medigaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcDvgtdvDw3zxL4TCEXxHKwC9MNjwcJI8',
    appId: '1:997215765874:ios:7b2b31fbd82c5e7d5449eb',
    messagingSenderId: '997215765874',
    projectId: 'medi-gaze-eec58',
    storageBucket: 'medi-gaze-eec58.appspot.com',
    iosBundleId: 'com.example.medigaze.RunnerTests',
  );
}
